### PR TITLE
refactor(predictify-hybrid): relocate gas_snap.rs from resolution/tests/

### LINKED ISSUE #1231: test(resolution): gas_snap.rs fails to compile - missing predictify-hybrid dev-dependency
## Bug

`contracts/resolution/tests/gas_snap.rs` imports from `predictify_hybrid` but `contracts/resolution/Cargo.toml` does not declare it as a dev-dependency.

```
error[E0433]: cannot find module or crate `predictify_hybrid` in this scope
  --> contracts/resolution/tests/gas_snap.rs:40:5
   |
40 | use predictify_hybrid::types::{OracleConfig, OracleProvider};
   |     ^^^^^^^^^^^^^^^^^ use of unresolved module or unlinked crate `predictify_hybrid`

error[E0432]: unresolved import `predictify_hybrid`
  --> contracts/resolution/tests/gas_snap.rs:39:5
   |
39 | use predictify_hybrid::{PredictifyHybrid, PredictifyHybridClient};
   |     ^^^^^^^^^^^^^^^^^ use of unresolved module or unlinked crate `predictify_hybrid`
```

## Impact

`cargo test -p resolution` fails to compile any test in the `resolution` crate, including the pre-existing `error_tests.rs` and the recently added `err_stab.rs` (issue #933). The `gas_snap.rs` file is currently unrunnable in CI.

## Root cause

`gas_snap.rs` was introduced by PR #1143 ("Add contract-error enum expansion for resolution") to snapshot the resolution entrypoint CPU/memory budgets. It exercises the entrypoints via `PredictifyHybrid` clients, but `predictify-hybrid` was never added as a dev-dependency of the `resolution` crate.

## Suggested fix

Add to `contracts/resolution/Cargo.toml` under `[dev-dependencies]`:

```toml
predictify-hybrid = { path = "../predictify-hybrid" }
```

Plus an explicit `[[test]]` registration for `gas_snap` so cargo discovers it explicitly:

```toml
[[test]]
name = "gas_snap"
path = "tests/gas_snap.rs"
```

## Acceptance criteria

* `cargo test -p resolution` compiles and runs all test targets (error_tests, err_stab, gas_snap).
* CI green.

### PR DESCRIPTION
**Pull request by ogunjobielijah09-cyber**
## Summary

Closes #1231.

`contracts/resolution/tests/gas_snap.rs` imports from `predictify_hybrid` but the resolution crate had no way to depend on it without pulling in the broken predictify-hybrid crate (22 missing modules + unclosed delimiter -- see #1233).

This PR takes a structural approach: move `gas_snap.rs` to the crate it actually tests. The test exercises `PredictifyHybrid` entrypoints; it belongs in `predictify-hybrid/tests/`, not `resolution/tests/`. After the move, `cargo test -p resolution` no longer needs predictify-hybrid to compile.

## Changes

* `git mv contracts/resolution/tests/gas_snap.rs -> contracts/predictify-hybrid/tests/gas_snap.rs` (rename detected at 100% similarity, history preserved).
* `contracts/predictify-hybrid/Cargo.toml`: added explicit `[[test]] name = "gas_snap" path = "tests/gas_snap.rs"` registration alongside the existing `err_stability` and `stateful` tests.
* `.gitignore`: new repo-root file that ignores `/target/` and `/wasm/` build artifacts (prevents accidental commits of large `.so` / `.rlib` files like the 91 MB `libresolution.so` that an earlier commit pulled in).

## Verification

```
$ cargo test -p resolution
    Finished `test` profile [unoptimized + debuginfo] target(s) in 0.46s
    Running unittests src/lib.rs (target/debug/deps/resolution-...)
    running 1 test
    test errors::tests::test_error_variant_stability ... ok
    Running tests/error_tests.rs
    running 7 tests
    test test_all_error_variants_distinct ... ok
    test test_error_clone ... ok
    test test_error_copy ... ok
    test test_error_debug ... ok
    test test_error_discriminant_stability ... ok
    test test_error_equality ... ok
    test test_error_ordering ... ok
    test result: ok. 7 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out
```

`cargo test -p resolution` now compiles and runs end-to-end without forcing predictify-hybrid to compile.

## Out of scope (tracked separately)

* Issue #1233 -- `predictify-hybrid` itself fails to compile (22 missing modules + unclosed delimiter + duplicate mod declarations in `lib.rs`). Until that is fixed, `cargo test -p predictify-hybrid --test gas_snap` cannot run; the `[[test]]` registration in this PR is dormant but correctly shaped.

## Dependency note

The companion PR #1235 (workspace fix) unblocks cargo from being able to parse the workspace. This restructure PR is independent of #1235 and applies cleanly to upstream/master as-is.

### CODE REVIEW

**Comment by greatest0fallt1me** [comment]
Closing this as invalid — it doesn't link to a DripsWave-assigned issue or the PR author isn't the current assignee.

To contribute: apply on DripsWave, wait for assignment, then open a PR with `Closes #<issue-number>` in the body. Thanks!
