### PR TITLE
refactor(predictify-hybrid): relocate gas_snap.rs from resolution/tests/

### LINKED ISSUE #1231: test(resolution): gas_snap.rs fails to compile - missing predictify-hybrid dev-dependency
## Bug

`contracts/resolution/tests/gas_snap.rs` imports from `predictify_hybrid` but `contracts/resolution/Cargo.toml` does not declare it as a dev-dependency.

```
error[E0433]: cannot find module or crate `predictify_hybrid` in this scope
  --> contracts/resolution/tests/gas_snap.rs:40:5
   |
40 | use predictify_hybrid::types::{OracleConfig, OracleProvider};
   |     ^^^^^^^^^^^^^^^^^ use of unresolved module or unlinked crate `predictify_hybrid`

error[E0432]: unresolved import `predictify_hybrid`
  --> contracts/resolution/tests/gas_snap.rs:39:5
   |
39 | use predictify_hybrid::{PredictifyHybrid, PredictifyHybridClient};
   |     ^^^^^^^^^^^^^^^^^ use of unresolved module or unlinked crate `predictify_hybrid`
```

## Impact

`cargo test -p resolution` fails to compile any test in the `resolution` crate, including the pre-existing `error_tests.rs` and the recently added `err_stab.rs` (issue #933). The `gas_snap.rs` file is currently unrunnable in CI.

## Root cause

`gas_snap.rs` was introduced by PR #1143 ("Add contract-error enum expansion for resolution") to snapshot the resolution entrypoint CPU/memory budgets. It exercises the entrypoints via `PredictifyHybrid` clients, but `predictify-hybrid` was never added as a dev-dependency of the `resolution` crate.

## Suggested fix

Add to `contracts/resolution/Cargo.toml` under `[dev-dependencies]`:

```toml
predictify-hybrid = { path = "../predictify-hybrid" }
```

Plus an explicit `[[test]]` registration for `gas_snap` so cargo discovers it explicitly:

```toml
[[test]]
name = "gas_snap"
path = "tests/gas_snap.rs"
```

## Acceptance criteria

* `cargo test -p resolution` compiles and runs all test targets (error_tests, err_stab, gas_snap).
* CI green.

### PR DESCRIPTION
**Pull request by ogunjobielijah09-cyber**
## Summary

Closes #1231.

`contracts/resolution/tests/gas_snap.rs` imported from `predictify_hybrid` but `predictify-hybrid` had no resolution->hybrid dependency declared. The naive "add `predictify-hybrid = { path = "../predictify-hybrid" }` to `[dev-dependencies]`" fix would force cargo to compile the broken predictify-hybrid crate (22 missing modules + unclosed delimiter in disputes.rs -- see #1233), breaking `cargo test -p resolution`.

This PR takes a structural approach instead: move `gas_snap.rs` to the crate it actually tests. The test exercises `PredictifyHybrid` entrypoints; it belongs in `predictify-hybrid/tests/`, not `resolution/tests/`. After the move, `cargo test -p resolution` no longer needs to compile predictify-hybrid.

## Changes

Two commits on branch `task/fix-resolution-gas-snap-deps`:

### Commit 1: `fix(workspace): remove malformed [workspace.members] blocks`

Pre-existing bug. The workspace root had two trailing malformed TOML tables that prevented cargo from parsing the workspace at all:

```
[workspace.members]
"contracts/auction"

[workspace.members]
"contracts/analytics"
```

These were invalid TOML (`error: key with no value, expected =`) and redundant with the top-level `[workspace].members` glob `"contracts/*"`. Removed both blocks. `Cargo.lock` regenerates with the now-correct package list.

### Commit 2: `refactor(predictify-hybrid): relocate gas_snap.rs from resolution/tests/`

* `git mv contracts/resolution/tests/gas_snap.rs -> contracts/predictify-hybrid/tests/gas_snap.rs` (rename detected at 100% similarity, history preserved).
* `contracts/predictify-hybrid/Cargo.toml`: added explicit `[[test]] name = "gas_snap" path = "tests/gas_snap.rs"` registration alongside the existing `err_stability` and `stateful` tests.
* `.gitignore`: new repo-root file that ignores `/target/` and `/wasm/` build artifacts (this also prevents the next contributor from accidentally committing `target/debug/deps/*.so` 91 MB files).

## Verification

```
$ cargo test -p resolution
    Finished `test` profile [unoptimized + debuginfo] target(s) in 0.46s
    Running unittests src/lib.rs (target/debug/deps/resolution-...)
    running 1 test
    test errors::tests::test_error_variant_stability ... ok
    Running tests/error_tests.rs
    running 7 tests
    test test_all_error_variants_distinct ... ok
    test test_error_clone ... ok
    test test_error_copy ... ok
    test test_error_debug ... ok
    test test_error_discriminant_stability ... ok
    test test_error_equality ... ok
    test test_error_ordering ... ok
    test result: ok. 7 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out
```

`cargo test -p resolution` now compiles and passes end-to-end (it did not before because gas_snap.rs was unrunnable in resolution).

## Out of scope (tracked separately)

* Issue #1233 — `predictify-hybrid` itself fails to compile (22 missing modules + unclosed delimiter + duplicate mod declarations in `lib.rs`). Until that is fixed, `cargo test -p predictify-hybrid --test gas_snap` cannot run; the `[[test]]` registration in commit 2 is dormant but correctly shaped.
* PR #1230 — adds `err_stab.rs` stability tests for the resolution crate (already merged via a separate branch).

## Reviewer note

A reviewer recommended splitting the two commits into two separate PRs (workspace fix on its own, restructure on its own) for cleaner single-concern review. If the maintainer prefers two PRs, the branch can be rebased and the PRs split off `master` independently — happy to do that as a follow-up if desired.

### CODE REVIEW

**Comment by ogunjobielijah09-cyber** [comment]
Superseded by two single-concern PRs per the reviewer recommendation:

* #1236 — workspace Cargo.toml fix (this PR's commit 1)
* #1237 — gas_snap.rs restructure (this PR's commit 2)

Both new PRs target `master` directly so they can be reviewed and merged independently.
